In [9]:
#Series are built on top of numpy arrays
import numpy as np
import pandas as pd

list_1 = ['a', 'b', 'c', 'd']
labels = [1,2,3,4]

ser_1 =pd.Series(data = list_1, index = labels)
arr_1 = np.array([1,2,3,4])
ser_2=pd.Series(arr_1)
display(ser_2)

dict_1 = { 1:'a', 2: 'b', 3:'c', 4: 'd'}
ser_3 = pd.Series(dict_1)          
display(ser_3)

0    1
1    2
2    3
3    4
dtype: int32

1    a
2    b
3    c
4    d
dtype: object

In [10]:
ser_2 +ser_2

0    2
1    4
2    6
3    8
dtype: int32

In [12]:
#pass series into numpy methods
np.exp(ser_2)

0     2.718282
1     7.389056
2    20.085537
3    54.598150
dtype: float64

In [14]:
#data frame creation using dictionary, lists and others
list_1 = ['a', 'b', 'c', 'd']
labels = [1,2,3,4]

ser_1 =pd.Series(data = list_1, index = labels)
arr_1 = np.array([1,2,3,4])
ser_2=pd.Series(arr_1)
display(ser_2)

dict_1 = { 1:'a', 2: 'b', 3:'c', 4: 'd'}
ser_3 = pd.Series(dict_1)          
display(ser_3)          

pd.DataFrame?

In [18]:
df_1 = pd.DataFrame(data =list_1, index =labels, columns =[ 'Col1'])
df_1

  Col1
1    a
2    b
3    c
4    d

In [23]:
df_2 = pd.DataFrame(data = ser_1, columns =['Col1'])
display(df_2)

  Col1
1    a
2    b
3    c
4    d

In [28]:
#dict_1 = { 1:'a', 2: 'b', 3:'c', 4: 'd'}
dict_1 = { 1:{'index1':'a'}, 2: {'index1':'b'}, 3:{'index1':'c'}, 4: {'index1':'d'}}
dict_1
df_3 = pd.DataFrame(data = dict_1)
display(df_3)

        1  2  3  4
index1  a  b  c  d

In [31]:
md_list = [[1,2,3], [4,5,6]]

In [35]:
df_3 = pd.DataFrame(data =md_list, index = ['index1', 'index2'], columns = ['col1', 'col2', 'col3'])
display(df_3)

        col1  col2  col3
index1     1     2     3
index2     4     5     6

In [43]:
df_3[['col1', 'col2']]
df_3.loc['index1']
df_3.loc['index1', 'col1']

1

In [48]:
d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d, index=['x', 'y', 'z'])
ser

x   NaN
y   NaN
z   NaN
dtype: float64

In [88]:
import pyodbc

server = 'LAPTOP-9IR70A88'
#host = localhost
database ='eCommerce'
#username = 'singl'
#password = '7506'

# cnxn = pyodbc.connect('DRIVER ={SQL Server};\
#                                                  SERVER='+server+';\
#                                                  DATABASE='+database';
#                                                  )
                                                 #UID= '+username+';\
                                                 #PWD='+password)
#ODBC Driver 17 for SQL Server;
#SQL Server Native Client 11.0
conn_str = (
    r'DRIVER=SQL Server;'
    r'SERVER=LAPTOP-9IR70A88;'
    r'PORT =1433;'
    r'DATABASE=eCommerce;'
    r'Trusted_Connection=yes;'
)

display(conn_str)

try: 
    cnxn = pyodbc.connect(conn_str)
    #df = pd.read_sql('SELECT * FROM SELECT * FROM [eCommerce].[dbo].[Currency]', con = cnxn)
    #display(df)
    display("Connected")
except Exception as e:
    print("Exception: {}".format(e))
finally:
    #cnxn.close()  
    cnxn.close()
    print("Connection CLosed)")

'DRIVER=SQL Server;SERVER=LAPTOP-9IR70A88;PORT =1433;DATABASE=eCommerce;Trusted_Connection=yes;'

Exception: ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect); [08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionOpen (Connect()). (53); [08001] [Microsoft][ODBC SQL Server Driver]Invalid connection string attribute (0)')

NameError: name 'cnxn' is not defined

In [59]:
import pyodbc 

a= [x for x in pyodbc.drivers()]
display(a)

['SQL Server',
 'SQL Anywhere 17',
 'PostgreSQL ANSI(x64)',
 'PostgreSQL Unicode(x64)',
 'SQL Server Native Client 11.0',
 'SQL Server Native Client RDA 11.0',
 'ODBC Driver 17 for SQL Server']

In [90]:
import pandas as pd
d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
df = pd.DataFrame(data=d, index=[0, 1, 2, 3])
display(df)

   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

In [116]:
import numpy as np

df.columns
df.dtypes
df.T
df.T.at['col1',0]
df.attrs
a=df.axes
df.iat[0,0]
df.index
df.loc[0,'col1']
df.ndim
df.size
df.style
df.values

array([[ 0., nan],
       [ 1., nan],
       [ 2.,  2.],
       [ 3.,  3.]])

In [118]:
df.agg(np.sum, axis =1)

0    0.0
1    1.0
2    4.0
3    6.0
dtype: float64

In [120]:
df.apply(lambda x: x*2, axis =0)

   col1  col2
0     0   NaN
1     2   NaN
2     4   4.0
3     6   6.0

In [121]:
df.apply(lambda x: x*2, axis =1)

   col1  col2
0   0.0   NaN
1   2.0   NaN
2   4.0   4.0
3   6.0   6.0

In [122]:
import  numpy as  np
import pandas as pd
from pandas_datareader import data as web
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
%matplotlib inline
import datetime as dt
import mplfinance as mpf

ModuleNotFoundError: No module named 'pandas_datareader'