# Assignment 3
All questions are weighted the same in this assignment. This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. All questions are worth the same number of points except question 1 which is worth 17% of the assignment grade.

**Note**: Questions 2-13 rely on your question 1 answer.

In [1]:
import pandas as pd
import numpy as np

# Filter all warnings. If you would like to see the warnings, please comment the two lines below.
import warnings
warnings.filterwarnings('ignore')

### Question 1
Load the energy data from the file `assets/Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](assets/Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **Energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable]`

Convert `Energy Supply` to gigajoules (**Note: there are 1,000,000 gigajoules in a petajoule**). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with parenthesis in their name. Be sure to remove these, e.g. `'Bolivia (Plurinational State of)'` should be `'Bolivia'`. Additionally, there are several countries with Numeric digits in their name. Make sure to remove these as well, e.g. `'Italy9'` should be `'Italy'`. 

Next, load the GDP data from the file `assets/world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `assets/scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries, and the rows of the DataFrame should be sorted by "Rank".*

In [2]:
def clean_country(country_name):
        #string =  'Bolivia9 (Plurinational State of)' 
        #print(country_first_name)
        #pattern = '([a-zA-Z]*)(?=[0-9])'
        
        string_array_len = len(country_name.split(sep = '('))
        #print("String split length", string_array_len)
       
        if  string_array_len>1:
            country_name =country_name.split(sep = '(')[0]
            country_name= country_name.strip()
            #print("Parenthesis cleaned, first name assigned",country_name)
        elif string_array_len <=1 :
            country_name = country_name
            #print(country_name) 
        #print(country_name)    
                
        import regex as re
        
        #pattern = '(^[a-zA-Z\s]*)(?=[0-9])'
        #pattern = '(^.*)(?=[0-9])'
        pattern ='(^[^0-9]*)(?=[0-9]+)'
        pattern_matches = re.findall(pattern, country_name )
        b = len(pattern_matches)
        
        #print("pattern_matches", b)
              
        if b >= 1:
            country_name = pattern_matches[0]
        elif b<1:
            country_name =country_name
        
        return country_name
    
def rename_country(a): 
        if a == "Korea, Rep.":
             a ="South Korea"
        elif a == "Iran, Islamic Rep.": 
            a= "Iran"
        elif a =="Hong Kong SAR, China":
            a="Hong Kong"
        elif a =="Republic of Korea":
            a="South Korea"
        elif a =="United States of America":
            a="United States"
        elif a =="United Kingdom of Great Britain and Northern Ireland":
            a="United Kingdom"
        elif a =="China, Hong Kong Special Administrative Region":
            a="Hong Kong"
        return a         
    
    #Load the energy data from the file assets/Energy Indicators.xls, which is a list of indicators of energy supply and renewable electricity production from the United Nations for the year 2013,
    #1. and should be put into a DataFrame with the variable name of Energy.
    #Keep in mind that this is an Excel file, and not a comma separated values file. 
    #2. Also, make sure to exclude the footer and header information from the datafile. 
    #3. The first two columns are unneccessary, so you should get rid of them, 
    #4. and you should change the column labels so that the columns are:
import pandas as pd
Energy = pd.read_excel(io = 'assets/Energy Indicators.xls', 
                                                 skiprows =18, 
                                                 usecols =[2,3,4,5],
                                                  header = None,
                                                  skipfooter =38,
                                                  names = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']) 
                                               #sheet_name = 0, header = )


#clean_country(country_name = 'Bolivia9 (Plurinational State of)')

import numpy as np
Energy[Energy['Country'].str.contains('Un')]
Energy['Country'] = Energy['Country'].apply(clean_country)
#Energy[Energy['Country'] =='Indonesia']
#print(Energy[Energy['Country'].str.contains('Un')])
Energy.replace(to_replace ="...", value = np.nan, inplace=True)
Energy['Energy Supply']=Energy['Energy Supply']*1000000

Energy['Country']=Energy['Country'].apply(rename_country)
#print(Energy)
#print(Energy[Energy['Country'].str.contains('Un')])
#print(Energy.iloc[216])

GDP = pd.read_csv('assets/world_bank.csv', skiprows = 4)
#GDP.head(2)
GDP['Country Name']=GDP['Country Name'].apply(rename_country)
#GDP[GDP['Country Name']=="South Korea"]
GDP.rename(columns={'Country Name':'Country'},inplace=True)

DataFrameScimEn = pd.read_excel(io = 'assets/scimagojr-3.xlsx')
GDP = GDP[['Country', 'Country Code', 'Indicator Name', 'Indicator Code', '2006', '2007', '2008', '2009','2010','2011', '2012','2013','2014', '2015']]
#GDP.head(2)
DataFrameScimEn['Rank'] = DataFrameScimEn['Rank'].astype('int32')
#type(DataFrameScimEn['Rank'])
#DataFrameScimEn.dtypes
#DataFrameScimEn=DataFrameScimEn[DataFrameScimEn['Rank'] <= 15]
#Energy.head(2)

#Merge the dataframes
first_merged=pd.merge(left = Energy, right  =GDP, how = 'inner', left_on ='Country', right_on = 'Country' )
#first_merged.head(2)
#first_merged[ ['Rank', 'Documents','Citable documents', 'Citations', 'Self-citations','Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']] 

#, '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015' ]]
second_merged=pd.merge(left = first_merged, right  =DataFrameScimEn, how = 'inner', left_on ='Country', right_on = 'Country' )
#second_merged
second_merged_before_filter = second_merged [['Rank','Country', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
#second_merged.columns
#second_merged_before_filter = second_merged[['Rank','Country', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
#second_merged_before_filter =second_merged
#print(len(second_merged_before_filter))
mask = second_merged_before_filter['Rank'] <= 15
final_df= second_merged_before_filter[mask]
final_df.set_index(keys = 'Country', inplace = True)
final_df.columns
def answer_one(dataframe=final_df):
# YOUR CODE HERE
    print(len(Energy))
    print(len(GDP))
    print(len(DataFrameScimEn))
    return(final_df.sort_values(by ="Rank", ascending =True))    
    raise NotImplementedError()

In [3]:
answer_one()

227
264
191

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [4]:
country_list = ['Australia', 'Bolivia', 'China', 'Hong Kong', 'China, Macao Special Administrative Region', 'Denmark', 'Falkland Islands', 'France', 'Greenland', 'Indonesia', 'Iran', 'Italy', 'Japan', 'Kuwait', 'Micronesia', 'Netherlands', 'Portugal', 'South Korea', 'Saudi Arabia', 'Serbia', 'Sint Maarten', 'Spain', 'Switzerland', 'Ukraine', 'United Kingdom', 'United States', 'Venezuela']

print(len(second_merged.columns))
#display(Energy.head(2))

for i in range(len(country_list)):
    if country_list[i] not in Energy['Country'].values.tolist():
        print(country_list[i])
#If Country is not in the index, replace index with ['Country] in the above line.

24

In [5]:
answer_one()

227
264
191

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [6]:
assert type(answer_one()) == pd.DataFrame, "Q1: You should return a DataFrame!"

assert answer_one().shape == (15,20), "Q1: Your DataFrame should have 20 columns and 15 entries!"

227
264
191
227
264
191

In [7]:
# Cell for autograder.

### Question 2
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*

In [8]:
%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

In [9]:
GDP.head(2)

,Country,Country Code,Indicator Name,Indicator Code,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
1,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN

In [10]:
def answer_two():
    #YOUR CODE HERE
    #Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). 
    
    first_merged_left_join=pd.merge(left = Energy, right =GDP, how = 'outer', left_on ='Country', right_on = 'Country' )
    
    
    first_merged_left_join.head(2)
    #first_merged_left_join[ ['Rank', 'Documents','Citable documents', 'Citations', 'Self-citations','Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']] 

    second_merged_left_join=pd.merge(left = first_merged_left_join, right  =DataFrameScimEn, how = 'outer', left_on ='Country', right_on = 'Country' )
    
    print("1. length of GDP", len(GDP))
    print(len(Energy))
    print(len(DataFrameScimEn))
   
    print("Outer join between 3", len(second_merged_left_join))
    
    print("Inner join between 3", len(second_merged ))
    
    x = (len(second_merged_left_join) - len(second_merged))
    
    print("difference between outer and inner", x)
    
    return (len(second_merged_left_join) - len(second_merged))
    raise NotImplementedError()

In [11]:
answer_two()

1. length of GDP 264
227
191
Outer join between 3 319
Inner join between 3 161
difference between outer and inner 158

158

In [12]:
assert type(answer_two()) == int, "Q2: You should return an int number!"

1. length of GDP 264
227
191
Outer join between 3 319
Inner join between 3 161
difference between outer and inner 158

### Question 3
What are the top 15 countries for average GDP over the last 10 years?

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [13]:
def answer_three():
    # YOUR CODE HERE
    # YOUR CODE HERE
    #type(GDP_2006_2015)
    #GDP_2006_2015 = final_df.drop(columns = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations','Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable'])
    GDP_2006_2015=answer_one()[['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015' ]]    
    #GDP_2006_2015 =GDP_2006_2015.set_index(keys = 'Country')
    #print(GDP_2006_2015.index)
    #GDP_2006_2015 = GDP_2006_2015.stack()
    #print(GDP_2006_2015.index)
    #GDP_2006_2015=GDP_2006_2015.groupby(level ="Country", axis = 0).mean()
    GDP_2006_2015['avgGDP'] = GDP_2006_2015.apply(np.nanmean,axis=1)
    df = round(GDP_2006_2015.sort_values(by='avgGDP',ascending=False),2)
    df = pd.Series(df['avgGDP'])

    def format_float(x):
        try:
           flt = float(x)
           return "{:,}".format(flt)
        except:
           return x
    
    df=df.apply(lambda x: format_float(x))
    print(df)
    return(df)
    raise NotImplementedError()

In [14]:
answer_three()

227
264
191
Country
United States         15,364,344,302,990.0
China                  6,348,608,932,836.1
Japan                 5,542,207,638,235.18
Germany               3,493,025,339,072.85
France                2,681,724,635,761.59
United Kingdom        2,487,906,661,418.42
Brazil                 2,189,794,143,774.9
Italy                 2,120,175,089,933.78
India                 1,769,297,396,603.86
Canada                1,660,647,466,307.51
Russian Federation    1,565,459,478,480.66
Spain                 1,418,078,278,145.69
Australia             1,164,042,729,991.43
South Korea           1,106,714,508,244.85
Iran                     444,155,754,051.1
Name: avgGDP, dtype: object

Country
United States         15,364,344,302,990.0
China                  6,348,608,932,836.1
Japan                 5,542,207,638,235.18
Germany               3,493,025,339,072.85
France                2,681,724,635,761.59
United Kingdom        2,487,906,661,418.42
Brazil                 2,189,794,143,774.9
Italy                 2,120,175,089,933.78
India                 1,769,297,396,603.86
Canada                1,660,647,466,307.51
Russian Federation    1,565,459,478,480.66
Spain                 1,418,078,278,145.69
Australia             1,164,042,729,991.43
South Korea           1,106,714,508,244.85
Iran                     444,155,754,051.1
Name: avgGDP, dtype: object

In [15]:
answer_three()

227
264
191
Country
United States         15,364,344,302,990.0
China                  6,348,608,932,836.1
Japan                 5,542,207,638,235.18
Germany               3,493,025,339,072.85
France                2,681,724,635,761.59
United Kingdom        2,487,906,661,418.42
Brazil                 2,189,794,143,774.9
Italy                 2,120,175,089,933.78
India                 1,769,297,396,603.86
Canada                1,660,647,466,307.51
Russian Federation    1,565,459,478,480.66
Spain                 1,418,078,278,145.69
Australia             1,164,042,729,991.43
South Korea           1,106,714,508,244.85
Iran                     444,155,754,051.1
Name: avgGDP, dtype: object

Country
United States         15,364,344,302,990.0
China                  6,348,608,932,836.1
Japan                 5,542,207,638,235.18
Germany               3,493,025,339,072.85
France                2,681,724,635,761.59
United Kingdom        2,487,906,661,418.42
Brazil                 2,189,794,143,774.9
Italy                 2,120,175,089,933.78
India                 1,769,297,396,603.86
Canada                1,660,647,466,307.51
Russian Federation    1,565,459,478,480.66
Spain                 1,418,078,278,145.69
Australia             1,164,042,729,991.43
South Korea           1,106,714,508,244.85
Iran                     444,155,754,051.1
Name: avgGDP, dtype: object

In [16]:
GDP_2006_2015 = answer_three()
# answer_three() returns a Series of avg GDPs sorted descending
# .stack() not needed and removed (Series.stack() removed in pandas 2.x)
a = GDP_2006_2015
display(type(a))
display(a.sort_values(ascending=False))

227
264
191
Country
United States         15,364,344,302,990.0
China                  6,348,608,932,836.1
Japan                 5,542,207,638,235.18
Germany               3,493,025,339,072.85
France                2,681,724,635,761.59
United Kingdom        2,487,906,661,418.42
Brazil                 2,189,794,143,774.9
Italy                 2,120,175,089,933.78
India                 1,769,297,396,603.86
Canada                1,660,647,466,307.51
Russian Federation    1,565,459,478,480.66
Spain                 1,418,078,278,145.69
Australia             1,164,042,729,991.43
South Korea           1,106,714,508,244.85
Iran                     444,155,754,051.1
Name: avgGDP, dtype: object

pandas.core.series.Series

Country
China                  6,348,608,932,836.1
Japan                 5,542,207,638,235.18
Iran                     444,155,754,051.1
Germany               3,493,025,339,072.85
France                2,681,724,635,761.59
United Kingdom        2,487,906,661,418.42
Brazil                 2,189,794,143,774.9
Italy                 2,120,175,089,933.78
United States         15,364,344,302,990.0
India                 1,769,297,396,603.86
Canada                1,660,647,466,307.51
Russian Federation    1,565,459,478,480.66
Spain                 1,418,078,278,145.69
Australia             1,164,042,729,991.43
South Korea           1,106,714,508,244.85
Name: avgGDP, dtype: object

In [17]:
assert type(answer_three()) == pd.Series, "Q3: You should return a Series!"

227
264
191
Country
United States         15,364,344,302,990.0
China                  6,348,608,932,836.1
Japan                 5,542,207,638,235.18
Germany               3,493,025,339,072.85
France                2,681,724,635,761.59
United Kingdom        2,487,906,661,418.42
Brazil                 2,189,794,143,774.9
Italy                 2,120,175,089,933.78
India                 1,769,297,396,603.86
Canada                1,660,647,466,307.51
Russian Federation    1,565,459,478,480.66
Spain                 1,418,078,278,145.69
Australia             1,164,042,729,991.43
South Korea           1,106,714,508,244.85
Iran                     444,155,754,051.1
Name: avgGDP, dtype: object

### Question 4
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [18]:
def answer_four():
    # YOUR CODE HERE
    GDP_2006_2015=GDP_2006_2015.sort_values(ascending = False).head(15)
    GDP_2006_2015[GDP_2006_2015.rank(axis =0)==6]
    GDPDifference = GDP.loc[GDP['Country Name']=='European Union', '2015'] -GDP.loc[GDP['Country Name']=='European Union', '2006']
    return GDPDIfference
    raise NotImplementedError()

In [19]:
# Cell for autograder.

### Question 5
What is the mean energy supply per capita?

*This function should return a single number.*

In [20]:
def answer_five():
    # YOUR CODE HERE
    #Energy['Energy Supply per Capita'].apply(type).unique()
    final_df['Energy Supply per Capita'].mean()
    raise NotImplementedError()

In [21]:
# Cell for autograder.

### Question 6
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*

In [22]:
def answer_six():
    # YOUR CODE HERE
    x = Energy[Energy['Energy Supply per Capita'].rank() ==1][['Country','% Renewable']].to_records(index=False)[0]
    return tuple(x)
    raise NotImplementedError()

In [23]:
assert type(answer_six()) == tuple, "Q6: You should return a tuple!"

assert type(answer_six()[0]) == str, "Q6: The first element in your result should be the name of the country!"

### Question 7
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [24]:
def answer_seven():
    # YOUR CODE HERE
    final_df['Ratio Citations'] = final_df['Self-citations']/final_df['Citations']
    #print(final_df['Ratio Citations'].head(2))
    type(final_df.sort_values(by = 'Ratio Citations', axis =0, ascending = False).head(1)['Ratio Citations'])
    solution= final_df.sort_values(by = 'Ratio Citations', axis =0, ascending = False).head(1)['Ratio Citations']
    #solution.values
    #print(solution)
    #print(solution.index)
    returnable = tuple(zip(solution.index, solution))
    return returnable[0]
    raise NotImplementedError()

In [25]:
assert type(answer_seven()) == tuple, "Q7: You should return a tuple!"

assert type(answer_seven()[0]) == str, "Q7: The first element in your result should be the name of the country!"

### Question 8

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return the name of the country*

In [26]:
def answer_eight():
    # YOUR CODE HERE
    final_df['Population']=final_df['Energy Supply']/final_df['Energy Supply per Capita']
    final_df.sort_values(by = 'Population', ascending = False, inplace = True)
    #final_df
    final_df['Rank based on Population'] = final_df['Population'].rank(method = 'max')
    returnable = str(final_df[final_df['Rank based on Population']==(len(final_df)-2)].index.values[0])
    return returnable
    raise NotImplementedError()

In [27]:
    final_df['Population']=final_df['Energy Supply']/final_df['Energy Supply per Capita']
    final_df.sort_values(by = 'Population', ascending = False, inplace = True)
    #final_df
    final_df['Rank based on Population'] = final_df['Population'].rank(method = 'max')
    returnable = str(final_df[final_df['Rank based on Population']==(len(final_df)-2)].index.values[0])
    display(returnable)
    display(final_df.head(2))

'United States'

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2009,2010,2011,2012,2013,2014,2015,Ratio Citations,Population,Rank based on Population
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.75491,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1.367645e+09,15.0
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.96908,...,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1.276731e+09,14.0

In [28]:
assert type(answer_eight()) == str, "Q8: You should return the name of the country!"

### Question 9
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

In [29]:
def answer_nine():
    # YOUR CODE HERE
    final_df['Citable docs per Person']=final_df['Citable documents']/final_df['Population']
    final_df.columns
    final_df [['Citable docs per Person', 'Energy Supply per Capita']]
    a=final_df [['Citable docs per Person', 'Energy Supply per Capita']].corr()
    a=a['Citable docs per Person']['Energy Supply per Capita']
    return(a)
    raise NotImplementedError()

In [30]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

In [31]:
plot9()

227
264
191

In [32]:
assert answer_nine() >= -1. and answer_nine() <= 1., "Q9: A valid correlation should between -1 to 1!"

### Question 10
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [33]:
def answer_ten():
    # YOUR CODE HERE
    final_df['Median Renewable Value'] = final_df['% Renewable'].median()
    final_df['HighRenew']= final_df['% Renewable']>= final_df['Median Renewable Value']
    final_df['HighRenew'].replace({True: 1, False:0}, inplace = True)
    final_df['HighRenew']
    returnable = final_df.sort_values(by = 'Rank', ascending = True)['HighRenew']
    #type(final_df.sort_values(by = 'Rank', ascending = True)['New Column'])
    return returnable
    raise NotImplementedError()

In [34]:
final_df['Median Renewable Value'] = final_df['% Renewable'].median()
final_df['HighRenew']= final_df['% Renewable']>= final_df['Median Renewable Value']
final_df['HighRenew'].replace({True: 1, False:0}, inplace = True)
final_df['HighRenew']
#display(final_df)
returnable = final_df.sort_values(by = 'Rank', ascending = True)['HighRenew']
 #type(final_df.sort_values(by = 'Rank', ascending = True)['New Column'])
display(returnable)

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                1
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: HighRenew, dtype: int64

In [35]:
assert type(answer_ten()) == pd.Series, "Q10: You should return a Series!"

In [36]:

#final_df.reset_index(inplace = True)
final_df.head(2)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2012,2013,2014,2015,Ratio Citations,Population,Rank based on Population,Citable docs per Person,Median Renewable Value,HighRenew
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.75491,...,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1.367645e+09,15.0,0.000093,17.02028,1
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.96908,...,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1.276731e+09,14.0,0.000012,17.02028,0

### Question 11
Use the following dictionary to group the Countries by Continent, then create a DataFrame that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [37]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

def answer_eleven():
    top15 = answer_one()
    # Ensure Country is the index for ContinentDict lookup
    if 'Country' in top15.columns:
        top15 = top15.set_index('Country')
    top15 = top15.copy()
    top15['PopEst'] = top15['Energy Supply'].values / top15['Energy Supply per Capita'].values
    top15['Continent'] = [ContinentDict.get(c, 'Other') for c in top15.index]
    result = top15.groupby('Continent')['PopEst'].agg(['size', 'sum', 'mean', 'std'])
    result.columns = ['size', 'sum', 'mean', 'std']
    return result

# Exploratory: add PopEst + Continent to final_df for cells below
top15_copy = answer_one()
if 'Country' in top15_copy.columns:
    top15_copy = top15_copy.set_index('Country')
top15_copy['PopEst'] = top15_copy['Energy Supply'].values / top15_copy['Energy Supply per Capita'].values
top15_copy['Continent'] = [ContinentDict.get(c, 'Other') for c in top15_copy.index]
x = top15_copy.groupby('Continent').agg({'PopEst': ['size','sum','mean','std']})
display(x)
final_df['PopEst'] = top15_copy['PopEst']

227
264
191

              PopEst
                size           sum          mean           std
Continent
Asia               5  2.898666e+09  5.797333e+08  6.790979e+08
Australia          1  2.331602e+07  2.331602e+07           NaN
Europe             6  4.579297e+08  7.632161e+07  3.464767e+07
North America      2  3.528552e+08  1.764276e+08  1.996696e+08
South America      1  2.059153e+08  2.059153e+08           NaN

In [38]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

#def answer_eleven():
    # YOUR CODE HERE
    #final_df.drop(columns = [ 'index'], inplace = True,axis =1)
final_df.head(2)
display(final_df.index.name)

if final_df.index.name ==  'Country' :
      final_df.reset_index(inplace =True)

#display(final_df.head(2))

final_df['Continent']=final_df['Country']
final_df['Continent'].replace(ContinentDict, inplace = True)

x=final_df.groupby(by = 'Continent').agg ({'Population' : ['size','sum','mean', 'std']})
print(x.shape)
final_df.head(2)
final_df.drop('Continent', axis = 1, inplace =True)
display(x)
display(x.info())
x.columns = x.columns.droplevel()
#x.droplevel(level ='Population', axis =1)
display(x)

'Country'

(5, 4)

              Population
                    size           sum          mean           std
Continent
Asia                   5  2.898666e+09  5.797333e+08  6.790979e+08
Australia              1  2.331602e+07  2.331602e+07           NaN
Europe                 6  4.579297e+08  7.632161e+07  3.464767e+07
North America          2  3.528552e+08  1.764276e+08  1.996696e+08
South America          1  2.059153e+08  2.059153e+08           NaN

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Asia to South America
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   (Population, size)  5 non-null      int64
 1   (Population, sum)   5 non-null      float64
 2   (Population, mean)  5 non-null      float64
 3   (Population, std)   3 non-null      float64
dtypes: float64(3), int64(1)
memory usage: 200.0+ bytes

None

               size           sum          mean           std
Continent
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN

In [39]:
assert type(answer_eleven()) == pd.DataFrame, "Q11: You should return a DataFrame!"

assert answer_eleven().shape[0] == 5, "Q11: Wrong row numbers!"

assert answer_eleven().shape[1] == 4, "Q11: Wrong column numbers!"

227
264
191
227
264
191
227
264
191

### Question 12
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a Series with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

In [40]:
def answer_twelve():
    top15 = answer_one()
    if 'Country' in top15.columns:
        top15 = top15.set_index('Country')
    top15 = top15.copy()
    top15['Continent'] = [ContinentDict.get(c, 'Other') for c in top15.index]
    top15['bins'] = pd.cut(top15['% Renewable'], 5)
    return top15.groupby(['Continent', 'bins'], observed=False)['% Renewable'].count()

answer_twelve()

227
264
191

Continent      bins
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
Australia      (2.212, 15.753]     1
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
               (42.701, 56.174]    0
               (56.174, 69.648]    0
North America  (2.212, 15.753]     1
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    1
South America  (2.212, 15.753]     0
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    1
Name: % Renewable, dtype: int64

In [41]:
bins = [0,20,40,60,80,100]
# Display cut result without modifying final_df (to avoid corrupting for answer_twelve)
temp_cut = pd.cut(final_df['% Renewable'].astype(float), bins)
display(temp_cut.head())

0     (0, 20]
1     (0, 20]
2     (0, 20]
3    (60, 80]
4     (0, 20]
Name: % Renewable, dtype: category
Categories (5, interval[int64, right]): [(0, 20] < (20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [42]:
final_df['Continent']=final_df['Country']
final_df['Continent'].replace(ContinentDict, inplace = True)
#print(final_df['Continent'])
final_df.set_index(keys = ['Continent', '% Renewable'], inplace = True)
x=final_df
#print(x.index)
y = x.groupby(level = [0,1]).agg({'Country' : ['count']})
display(type(y))
#print(y.columns)
#print(y.index)
#print(y['Country']['count'])
#z =y[y['Country']['count'] !=0]
print(y)
print(len(y))
final_df.reset_index(inplace = True)
final_df.drop(['Continent'], axis=1, inplace=True, errors='ignore') #Cleanup 
final_df.head(2)

pandas.core.frame.DataFrame

                          Country
                            count
Continent     % Renewable
Asia          2.279353          1
              5.707721          1
              10.232820         1
              14.969080         1
              19.754910         1
Australia     11.810810         1
Europe        10.600470         1
              17.020280         1
              17.288680         1
              17.901530         1
              33.667230         1
              37.968590         1
North America 11.570980         1
              61.945430         1
South America 69.648030         1
15

,% Renewable,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,...,2013,2014,2015,Ratio Citations,Population,Rank based on Population,Citable docs per Person,Median Renewable Value,HighRenew,PopEst
0,19.75491,China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,...,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1.367645e+09,15.0,0.000093,17.02028,1,1.367645e+09
1,14.96908,India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,...,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1.276731e+09,14.0,0.000012,17.02028,0,1.276731e+09

In [43]:
z =pd.Series(y['Country']['count'])
type(z)
z
#type(answer_twelve())

Continent      % Renewable
Asia           2.279353       1
               5.707721       1
               10.232820      1
               14.969080      1
               19.754910      1
Australia      11.810810      1
Europe         10.600470      1
               17.020280      1
               17.288680      1
               17.901530      1
               33.667230      1
               37.968590      1
North America  11.570980      1
               61.945430      1
South America  69.648030      1
Name: count, dtype: int64

In [44]:
assert type(answer_twelve()) == pd.Series, "Q12: You should return a Series!"

assert len(answer_twelve()) == 25, "Q12: Wrong result numbers!"

227
264
191
227
264
191

In [45]:
final_df.head(2)

,% Renewable,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,...,2013,2014,2015,Ratio Citations,Population,Rank based on Population,Citable docs per Person,Median Renewable Value,HighRenew,PopEst
0,19.75491,China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,...,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1.367645e+09,15.0,0.000093,17.02028,1,1.367645e+09
1,14.96908,India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,...,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1.276731e+09,14.0,0.000012,17.02028,0,1.276731e+09

### Question 13
Convert the Population Estimate series to a string with thousands separator (using commas). Use all significant digits (do not round the results).

e.g. 12345678.90 -> 12,345,678.90

*This function should return a series `PopEst` whose index is the country name and whose values are the population estimate string*

In [46]:
def answer_thirteen():
    import pandas as pd
    if 'PopEst' not in final_df.columns:
        final_df['PopEst'] = final_df['Energy Supply'] / final_df['Energy Supply per Capita']
    pop_est = pd.to_numeric(final_df['PopEst'], errors='coerce')
    return pop_est.apply(lambda x: '{:,.2f}'.format(x) if pd.notna(x) else x)

answer_thirteen()

0     1,367,645,161.29
1     1,276,730,769.23
2       317,615,384.62
3       205,915,254.24
4       143,500,000.00
5       127,409,395.97
6        80,369,696.97
7        77,075,630.25
8        63,870,967.74
9        63,837,349.40
10       59,908,256.88
11       49,805,429.86
12       46,443,396.23
13       35,239,864.86
14       23,316,017.32
Name: PopEst, dtype: object

In [47]:
final_df.loc[:,"PopEst"]

0     1.367645e+09
1     1.276731e+09
2     3.176154e+08
3     2.059153e+08
4     1.435000e+08
5     1.274094e+08
6     8.036970e+07
7     7.707563e+07
8     6.387097e+07
9     6.383735e+07
10    5.990826e+07
11    4.980543e+07
12    4.644340e+07
13    3.523986e+07
14    2.331602e+07
Name: PopEst, dtype: float64

In [48]:
final_df.head(2)
#final_df['Population']
#final_df.set_index(keys ="Country", inplace = True)
final_df.head(2)
#a = '{:,}'.format(final_df['Population'])
final_df.info()
if final_df.dtypes['PopEst'] != 'O':
    final_df.loc[:,"PopEst"] = final_df["PopEst"].map('{0:,.2f}'.format)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   % Renewable               15 non-null     float64
 1   Country                   15 non-null     object
 2   Rank                      15 non-null     int32
 3   Documents                 15 non-null     int64
 4   Citable documents         15 non-null     int64
 5   Citations                 15 non-null     int64
 6   Self-citations            15 non-null     int64
 7   Citations per document    15 non-null     float64
 8   H index                   15 non-null     int64
 9   Energy Supply             15 non-null     float64
 10  Energy Supply per Capita  15 non-null     float64
 11  2006                      15 non-null     float64
 12  2007                      15 non-null     float64
 13  2008                      15 non-null     float64
 14  2009                      15 non-null     float64
 15  2010                      15 non-null     float64
 16  2011                      15 non-null     float64
 17  2012                      15 non-null     float64
 18  2013                      15 non-null     float64
 19  2014                      15 non-null     float64
 20  2015                      14 non-null     float64
 21  Ratio Citations           15 non-null     float64
 22  Population                15 non-null     float64
 23  Rank based on Population  15 non-null     float64
 24  Citable docs per Person   15 non-null     float64
 25  Median Renewable Value    15 non-null     float64
 26  HighRenew                 15 non-null     int64
 27  PopEst                    15 non-null     float64
dtypes: float64(20), int32(1), int64(6), object(1)
memory usage: 3.4+ KB

In [49]:
#final_df['Population'].

"12312312.123123".format("{0:,.2f}")

'12312312.123123'

In [50]:
final_df["PopEst"]

0     1,367,645,161.29
1     1,276,730,769.23
2       317,615,384.62
3       205,915,254.24
4       143,500,000.00
5       127,409,395.97
6        80,369,696.97
7        77,075,630.25
8        63,870,967.74
9        63,837,349.40
10       59,908,256.88
11       49,805,429.86
12       46,443,396.23
13       35,239,864.86
14       23,316,017.32
Name: PopEst, dtype: object

In [51]:
final_df['Population']

0     1.367645e+09
1     1.276731e+09
2     3.176154e+08
3     2.059153e+08
4     1.435000e+08
5     1.274094e+08
6     8.036970e+07
7     7.707563e+07
8     6.387097e+07
9     6.383735e+07
10    5.990826e+07
11    4.980543e+07
12    4.644340e+07
13    3.523986e+07
14    2.331602e+07
Name: Population, dtype: float64

In [52]:
final_df.columns

Index(['% Renewable', 'Country', 'Rank', 'Documents', 'Citable documents',
       'Citations', 'Self-citations', 'Citations per document', 'H index',
       'Energy Supply', 'Energy Supply per Capita', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       'Ratio Citations', 'Population', 'Rank based on Population',
       'Citable docs per Person', 'Median Renewable Value', 'HighRenew',
       'PopEst'],
      dtype='object')

In [53]:
final_df

,% Renewable,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,...,2013,2014,2015,Ratio Citations,Population,Rank based on Population,Citable docs per Person,Median Renewable Value,HighRenew,PopEst
0,19.754910,China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,...,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1.367645e+09,15.0,0.000093,17.02028,1,"1,367,645,161.29"
1,14.969080,India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,...,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1.276731e+09,14.0,0.000012,17.02028,0,"1,276,730,769.23"
2,11.570980,United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,...,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,3.176154e+08,13.0,0.000298,17.02028,0,"317,615,384.62"
3,69.648030,Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,...,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,2.059153e+08,12.0,0.000042,17.02028,1,"205,915,254.24"
4,17.288680,Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,...,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,1.435000e+08,11.0,0.000128,17.02028,1,"143,500,000.00"
5,10.232820,Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,...,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,1.274094e+08,10.0,0.000238,17.02028,0,"127,409,395.97"
6,17.901530,Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,...,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,8.036970e+07,9.0,0.000209,17.02028,1,"80,369,696.97"
7,5.707721,Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,...,4.445926e+11,4.639027e+11,NaN,0.332782,7.707563e+07,8.0,0.000114,17.02028,0,"77,075,630.25"
8,10.600470,United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,...,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,6.387097e+07,7.0,0.000319,17.02028,0,"63,870,967.74"
9,17.020280,France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,...,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,6.383735e+07,6.0,0.000203,17.02028,1,"63,837,349.40"
10,33.667230,Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,...,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,5.990826e+07,5.0,0.000180,17.02028,1,"59,908,256.88"
11,2.279353,South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,...,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,4.980543e+07,4.0,0.000239,17.02028,0,"49,805,429.86"
12,37.968590,Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,...,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,4.644340e+07,3.0,0.000201,17.02028,1,"46,443,396.23"
13,61.945430,Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,...,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,3.523986e+07,2.0,0.000500,17.02028,1,"35,239,864.86"
14,11.810810,Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,...,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,2.331602e+07,1.0,0.000374,17.02028,0,"23,316,017.32"

In [54]:
assert type(answer_thirteen()) == pd.Series, "Q13: You should return a Series!"

assert len(answer_thirteen()) == 15, "Q13: Wrong result numbers!"

### Optional

Use the built in function `plot_optional()` to see an example visualization.

In [55]:
def plot_optional():
    import matplotlib as plt
    %matplotlib inline
    Top15 = answer_one()
    ax = Top15.plot(x='Rank', y='% Renewable', kind='scatter', 
                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
                    xticks=range(1,16), s=6*Top15['2014']/10**10, alpha=.75, figsize=[16,6]);

    for i, txt in enumerate(Top15.index):
        ax.annotate(txt, [Top15['Rank'][i], Top15['% Renewable'][i]], ha='center')

    print("This is an example of a visualization that can be created to help understand the data. \
This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
2014 GDP, and the color corresponds to the continent.")